services:
  - type: web
    name: nakshatra-designer
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
